#!/usr/bin/env sh

# global settings
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6
yabai -m config window_origin_display        cursor
yabai -m config auto_balance             	 on
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50

## mouse settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus

# move/resize windows by holding alt, clicking, and dragging
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off

# disable certain types of windows
yabai -m rule --add subrole="Dialog|Floating" manage=off

borders active_color=0xffff0000 width=10.0 &
