require("nerdo.profiling")
require("nerdo.functions")
require("nerdo.keymap")
require("nerdo.options")
require("nerdo.lazy")
require("nerdo.gui")
require("nerdo.workspace")
require("nerdo.persistent-undo")
